title: XPRIZE Quantum Application: Quantum for Graph Problems
description: This is the official website for the team of QuantumForGraphproblem in XPRIZE Quantum Application Competition.
author: "Jianqiang Li"

theme: minima

base_url: qlsapp
repository: jianqiang206/qlsapp

# Minima social links
github_username: jianqiang206
linkedin_username: jianqiang Li
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
